export { default as Task1 } from './Task1'
export { default as Task2 } from './Task2'
export { default as Task3 } from './Task3'
export { default as Task4 } from './Task4'
export { default as Task5 } from './Task5'